---
title: "Untitled"
author: "Filip Schouwenaars"
date: "January 25, 2016"
output: html_document
---

This is an example exercise.

```{r, ex=create_a, type=pre-exercise-code}
b = 5
```

```{r, ex=create_a, type=sample-code}
# Create a variable a, equal to 5


# Print out a

```

```{r, ex=create_a, type=solution}
# Create a variable a, equal to 5
a = 5

# Print out a
a
```

```{r}
# Normal R Code trying to break things.
```

```{r, ex=create_a, type=sct}
test_object("a")
test_output_contains("a", incorrect_msg = "Make sure to print `a`")
success_msg("Great!")
```

```{r, ex=create_a, type=hint}
Try something else
```

You can include a second exercise as well, like this: a sample code, solution code and sct suffise:

```{r, ex=create_x, type=sample-code}
# Create the variable x, as rnorm(100)


# Print out length of x

```

```{r, ex=create_x, type=solution}
# Create a variable x, as rnorm(100)
x = rnorm(100)

# Print out a
length(x)
```

```{r, ex=create_x, type=sct}
test_function("rnorm")
test_output_contains("100", incorrect_msg = "Have you printed out the length of `x`?")
success_msg("Great!")
```


