---
title: "Untitled"
author: "Filip Schouwenaars"
date: "January 25, 2016"
output: html_document
---

This is an example exercise.

```{r, ex=create_a, type=pre-exercise-code}
b = 5
```

```{r, ex=create_a, type=sample-code}
# Create a variable a, equal to 5


# Print out a

```

```{r, ex=create_a, type=solution}
# Create a variable a, equal to 5
a = 5

# Print out a
a
```

```{r}
# Normal R Code trying to break things.
```

```{r, ex=create_a, type=sct}
test_object("a")
test_output_contains("a", incorrect_msg = "Make sure to print `a`")
success_msg("Great!")
```

```{r, ex=create_a, type=hint}
Here is a hint: use `<-` for assignment
```

You can include a second exercise as well, like this: a sample code, solution code and sct suffise:

```{r, ex=create_x, type=sample-code}
# Create a variable x, equal to 9


# Print out x

```

```{r, ex=create_x, type=sample-code}
# Duplicate to test things
```

```{r, ex=create_x, type=solution}
# Create a variable x, equal to 9
x <- 9

# Print out x
x
```

```{r, ex=create_x, type=sct}
test_object("x")
test_output_contains("x")
success_msg("Nice")
```

```{r, ex=create_x, type=hint}
This time you should create the variable x
```

